### ISSUE TITLE
アーキテクチャ設計の方針を決定・共有

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-server#15]
## 目的
- 無闇にコードを書き始めると，関心ごとの切り分けに失敗し，特定のファイルが膨大になるので，アーキテクチャ設計方針（MVC など）を検討

## 終了条件
- どのようなアーキテクチャ設計が存在するのかを大まかに整理
- URL などを基に，調査した結果を報告し，議論

**Comment by xiii111** [comment]
## 検討アーキテクチャ
　Golang，API，DB という特徴を持つシステムにおける設計で調べた．多くの設計があったが，どの設計も DI（Dependency Injection）の考え方に基づいているよう．つまりあるレイヤは特定のレイヤに依存する，という関係で成り立っている．どの設計も共通して以下のようなメリットがあるみたい
- 変更を加える際に，どこに書けば良いかが明確
- 関心ごとに切り分けができているため，コード理解がしやすい

個人的なデメリットは
- 実装するコスト（各設計への理解も含める）が高い

以下に検討した設計を示す．

#### クリーンアーキテクチャ
- https://qiita.com/muroon/items/8add8da911341312176d

#### レイヤードアーキテクチャ
- https://qiita.com/dich1/items/0871c9c1ff058d0d693b
- https://qiita.com/yuukiyuuki327/items/238814326964e06dd655

#### オニオンアーキテクチャ
- https://qiita.com/little_hand_s/items/2040fba15d90b93fc124
- https://qiita.com/hmarf/items/7f4d39c48775c205b99b

全て読んでもらえると，雰囲気だけはわかるかもしれない．実際に自分も限られた時間では，理解が及ばないところがほとんどだった．
でも，この3つに共通していたのが，大きく分けて4つの層があること．自分なりの命名をすると，

1. handler 層

クライアントからのリクエストを受け付けて，適切な処理を割り当てる．MVC でいうと View にあたる．ユーザーインターフェイス層などの名前でもしっくり来る

2. usecase 層

この層の役割は，ソフトウェアが行うことになっている仕事を定義する層と書かれているが，いまいちピンと来ていない．アプリケーション層とも言われていて，MVC の Controller にあたるよう．ということはロジックを書くところと考えて，Model の値をとってきて色々いじる層か？

3. domain 層

この層では，Model を主に管理するよう．次に示す infra 層を通して DB からとったデータを構造体として持っている．usecase から求められるデータを提供する．

4. infra 層

この層では，DB と通信し，値を確保する．ORM（ググれば出る）的な働きか？そうなると，今回導入した pop は ORM としての機能を持っているので，いらないのかもしれない．

以上のようにわかる範囲で解説したが，正直深く理解できていな状態．でも要は，リクエストをうまいこと捌く handler 層，domain 層からデータを取って，handler 層に渡す usecase 層，infra 層を通して DB からデータをとって，usecase 層にデータを渡す domain 層がある．

本プロジェクトでは，以上の層から必要な層を用意して切り分けようと思う．

**Comment by xiii111** [comment]
@takasusuke @takesi0627 レビューお願いします．レビューして欲しい点としては，記述した内容の理解と，添付した URL を用いたアーキテクチャの概要理解をした上で，どのような設計がいいかのコメントです．

また，色々調べた結果，実装をしながら手探りで考える点が多いので，まず #8 を実装して，そこからアーキテクチャに切り分ける方が手順的には良いと思いました．モデル部分の実装が一切ない状態で設計するには，今の理解では浅すぎるからです．なので，ここでの議論をしながら， #8 にとりくもうと思いますが良いでしょうか？

**Comment by takasusuke** [comment]
ふむふむ。
実装あった方がこちらもわかりやすいのでやりやすいように#8 を進めて良いと思います。

**Comment by takesi0627** [comment]
> #8 にとりくもうと思いますが良いでしょうか？

いいと思います。

**Comment by xiii111** [comment]
@takesi0627 @takasusuke ありがとう．それではこのイシューのレビューはゆっくりで大丈夫です．今週のこの後は #8 をやります

**Comment by takasusuke** [comment]
いろいろ勉強したので、共有も兼ねてまとめます。
### 各層について
自分の理解はこんな感じ。
- handler層(view, UI)
(例). ユーザがアプリ上でランキング表示ボタンを押した時、usecase層にボタン押下イベントを知らせる
- usecase層(controller, application)
(例). ボタン押下イベントを受け取り、ランキングデータ取得リクエストをdomain層に送る。ただし、デバイスの大きさを考慮して上位10件だけリクエストするとか、直前のボタン押下イベントから1秒も経過していないので反応しないとかのアプリ依存の処理を記述する
- domain層(model)
(例). データベースの処理を記述してランキングを取得する。総データが10件未満のうちはランキングを機能させない(0件のリクエストを返す)とかのシステム依存の処理を記述する。
- infra層(databaseとかAPI)
(例) MySQL, postgre

アーキテクチャやサイトによっては[domain層]が[presentation層とdomain層]になっているんだけど、presentation層の役割が正直よくわからなかった。。。

### アーキテクチャについて
(->は依存関係)
- レイヤードアーキテクチャ
handler -> usecase -> domain -> infra
- オニオンアーキテクチャ(クリーンアーキテクチャも本質的には同じ)
handler & infra -> usecase -> domain 
依存関係と処理の流れが異なる(コードが複雑になる)が、infra層に依存せずに済む

データベースを別のものにする予定が無いと思ったので、infra層に依存する形にはなりますが、レイヤードアーキテクチャが考え方もわかりやすくて良いと思いました。
ただ、popは`PostgreSQL, MySQL, SQLite, CockroachDB`に対応しているそうなので、データベース処理記述にpopを使うなら、これらのデータベース間で互換性があると思います。
そういう意味で実態として、若干オニオンアーキテクチャになるのでは？って感じです。

**Comment by takasusuke** [comment]
usecase層とdomain層の役割の違いはこれがわかりやすかった。
https://ikenox.info/blog/validation-in-clean-arch/

**Comment by xiii111** [comment]
> 各層について

は，アプリサイドの話を書いてくれたのかな？今回はサーバサイドだから，

> ユーザがアプリ上でランキング表示ボタンを押した時、usecase層にボタン押下イベントを知らせる

は，api にリクエストが飛んできたら，usecase 層の対応する処理にリクエスト情報を知らせる，かな．

> ボタン押下イベントを受け取り、ランキングデータ取得リクエストをdomain層に送る。ただし、デバイスの大きさを考慮して上位10件だけリクエストするとか、直前のボタン押下イベントから1秒も経過していないので反応しないとかのアプリ依存の処理を記述する

リクエストを受け取り，必要に応じて加工し，取得するデータのリクエストを domain 層におくる．

とかになるのかな？

**Comment by takasusuke** [comment]
例に上げてくれた文脈でのアーキテクチャって、サーバサイドとクライアントサイドの処理の流れに関する話だと勘違いしてたけど、サーバサイド単体とかの処理の流れもこの文脈でのアーキテクチャって呼ぶ？ってこと？

それベースで考え直すだけなのでいくつか確認すると
パラメータとともにデータ追加とかのリクエストが来ました。
パラメータを復元します。
復元したパラメータを良い感じに加工します。
加工したものをデータベースにしまいます。
みたいな処理をこのアーキテクチャに当てはめるならどうするかってこと？

**Comment by takasusuke** [comment]
apiとdbのやりとりも調べてた例にあったし、確かに言うのか。

infra層についての考えは変わらないので、考え方としてはレイヤードアーキテクチャが良いと思うんですが、どの処理がusecase層でどの処理がdomain層かを決めたいということですか？
(handler層はあってないものだと思ってる。リクエスト来たよー的な層。)

**Comment by xiii111** [comment]
> サーバサイド単体とかの処理の流れもこの文脈でのアーキテクチャって呼ぶ？ってこと？

単純にアプリケーションの設計をアーキテクチャと呼ぶと思います．api も モバイルアプリも各々設計があります．Unity は・・・View が GUI になっていて，Controller が Director，Model は実質無いみたいな設計ですかね

> パラメータとともにデータ追加とかのリクエストが来ました。
> パラメータを復元します。
> 復元したパラメータを良い感じに加工します。
> 加工したものをデータベースにしまいます。
> みたいな処理をこのアーキテクチャに当てはめるならどうするかってこと？

そうだね．けど今行ってくれた各文章をそれぞれ当てはめれば良い感じにはなるよね

> infra層についての考えは変わらないので、考え方としてはレイヤードアーキテクチャが良いと思います。

今回，インフラ層の主軸になる SQL を叩くというのが，ORM に代替されているので，インフラ層は現時点で記述するものはないのかも？（通信処理とかか？）とりあえず，レイヤードアーキテクチャ押しということで，こちらにフィーチャーしようと思います．個人的にはオニオンもいい感じに見えたので，こっちも考慮します

**Comment by takasusuke** [comment]
> > サーバサイド単体とかの処理の流れもこの文脈でのアーキテクチャって呼ぶ？ってこと？
> 
> 単純にアプリケーションの設計をアーキテクチャと呼ぶと思います．api も モバイルアプリも各々設計があります．モバイルアプリ側（Unity）は・・・View が GUI になっていて，Controller が Director，Model は実質無いみたいな設計ですかね．つまり今回のアーキテクチャはサーバサイド独立な話

オニオンアーキテクチャとか初めて聞いたので、なんかこれらの用語はクライアント-サーバサイドに限定して使われる用語だと思ったわ笑

> 
> > パラメータとともにデータ追加とかのリクエストが来ました。
> > パラメータを復元します。
> > 復元したパラメータを良い感じに加工します。
> > 加工したものをデータベースにしまいます。
> > みたいな処理をこのアーキテクチャに当てはめるならどうするかってこと？
> 
> そうだね．けど今言ってくれた各文章をそれぞれ当てはめれば良い感じにはなるよね
> 

え？あ、そうなるか。Modelの特性由来の処理記述(ex.挑戦回数は65535超えないとか?)はdomainで、それ以外は全てusecaseって感じに思ってる。

> > infra層についての考えは変わらないので、考え方としてはレイヤードアーキテクチャが良いと思います。
> 
> 今回，インフラ層の主軸になる SQL を叩くというのが，ORM に代替されているので，インフラ層は現時点で記述するものはないのかも？（通信処理とかか？）とりあえず，レイヤードアーキテクチャ押しということで，こちらにフィーチャーしようと思います．個人的にはオニオンもいい感じに見えたので，こっちも考慮します

インフラ層に当てはまるものが今見えないので、それならレイヤードアーキテクチャとオニオンアーキテクチャ同じでは？って感じなので、それなら考え方が単純なレイヤードアーキテクチャ推しなだけで、インフラ層が具体的にあるなら設計的にはオニオン推しです。

**Comment by xiii111** [comment]
> Modelの特性由来の処理記述(ex.挑戦回数は65535超えないとか?)はdomainで、それ以外は全てusecaseって感じに思ってる。

あ，そうだね！

> インフラ層に当てはまるものが今見えないので、それならレイヤードアーキテクチャとオニオンアーキテクチャ同じでは？って感じなので、考え方が単純なレイヤードアーキテクチャ推しなだけで、インフラ層が具体的にあるなら設計的にはオニオン推しです。

おけ！正直，これらの考え方の違いを全然汲み取れてないので，要勉強って感じです，ありがとう！

**Comment by takesi0627** [comment]
コメント読んだけど、要はMVCで考えればいいのかな
M＝domain + infra
V = handler
C = use case

**Comment by xiii111** [comment]
ごめん，不適切な表現をしたな．
MVCとDDDはデータフローが違う．MVCだと，ユーザインプットがCに行く（アプリなら画面タップとか）
https://qiita.com/koutalou/items/07a4f9cf51a2d13e4cdc 参照

**Comment by takesi0627** [comment]
> ごめん，不適切な表現をしたな．
> MVCとDDDはデータフローが違う．MVCだと，ユーザインプットがCに行く（アプリなら画面タップとか）
> https://qiita.com/koutalou/items/07a4f9cf51a2d13e4cdc 参照

なるほど、これはわかりやすいね

**Comment by xiii111** [comment]
アーキテクチャ設計の導入 #7 の時間を2時間分使って，ここに設計の仕様をまとめるつもりです．つまり見積もりでは，アーキテクチャ設計の導入 #7 は `2` のタスクとなるということです．理想通りに行くかは分かりませんが，頑張ります

**Comment by xiii111** [comment]
@takasusuke 
> インフラ層に当てはまるものが今見えないので、それならレイヤードアーキテクチャとオニオンアーキテクチャ同じでは？って感じなので、考え方が単純なレイヤードアーキテクチャ推しなだけで、インフラ層が具体的にあるなら設計的にはオニオン推しです。

これは完全に理解した．
最新のレイヤードアーキテクチャと，オニオンアーキテクチャの違いは，*Domain 層が Infrastructure層に依存しているかどうか* ってことだね

**Comment by xiii111** [comment]
@takasusuke @takesi0627 
再レビューをお願いします（できなくてもいい）
今回はオニオンアーキテクチャを利用しようかなと考えています．

### レイヤ
- `interface` 層

リクエストをハンドリングして，各用途に対応する `usecase` を呼び出す

- `application`（`usecase`）層

どのような処理が求められているかを理解し，`domain 層` からデータを受け取る

- `domain` 層

ドメインロジックを記述する．今回では，`Player`と`Record`というドメインの仕様を決め，`usecase` 層へ適切なデータを返す

- `infrastructure` 層

データベースとのやり取りを記述する．今回は，ORM の文法を利用してやり取りする．`domain` 層にある仕様を実装する

### 参考 URL
- [オニオンアーキテクチャとは？](https://little-hands.hatenablog.com/entry/2017/10/11/075634)（理論なのでコードはありません）
- [golang のコードと共にオニオンアーキテクチャを理解できる記事](https://qiita.com/tono-maron/items/345c433b86f74d314c8d)（記事内ではレイヤードアーキテクチャと書かれているが，厳密にはオニオンアーキテクチャのことだと思われる）
- [ORM とオニオンアーキテクチャの融合](https://qiita.com/nanamen/items/f37d1047368929e377fd)（この例では，ORM に gorm というものが使われています）
- [同様な例](https://engineer.recruit-lifestyle.co.jp/techblog/2018-03-16-go-ddd/)（気が向いたら見てください程度）

**Comment by takesi0627** [comment]
コメントだけ読みました。あとはプルリク出してからにします。

**Comment by xiii111** [comment]
こちら，#26 に適用した．大体設計案については収束していると判断して閉じます
